services:
  database:
    image: postgres:18.0
    container_name: db
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INIT_ARGS: ${POSTGRES_INIT_ARGS}
    volumes:
      - ../migrations/2025-11-08-171112-0000_create_users/up.sql:/docker-entrypoint-initdb.d/up.sql
    networks:
      - mantis_network

  pgadmin:
    image: dpage/pgadmin4:9.9
    restart: always
    container_name: pgadmin4
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    networks:
      - mantis_network

  rust:
    build: .
    restart: always
    container_name: rust
    depends_on:
      - database
      - pgadmin
    volumes:
      - ../:/data/
    working_dir: /data
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    networks:
      - mantis_network

networks:
  mantis_network:
    driver: bridge
